<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>true</ImplicitUsings>
        <IncludeSymbols>true</IncludeSymbols>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Marc Wittke</Authors>
        <Company>anic GmbH</Company>
        <Copyright>All rights reserved. Distributed under the terms of the MIT License.</Copyright>
        <Description>Abstractions of Backend.Fx persistence.</Description>
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
        <PackageLicense>MIT</PackageLicense>
        <PackageProjectUrl>https://github.com/backend-fx/Backend.Fx.Persistence</PackageProjectUrl>
        <Product>Backend.Fx</Product>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/backend-fx/Backend.Fx.Persistence.git</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Backend.Fx.Execution" Version="1.1.11" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
        <PackageReference Include="NodaTime" Version="3.3.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Backend.Fx.Persistence\Backend.Fx.Persistence.csproj"/>
    </ItemGroup>

</Project>
