name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  nuke-build:
    name: nuke-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: nuke build
        run: ./build.sh publish
        env:
            MYGET_APIKEY: ${{ secrets.MYGET_APIKEY }}
            NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
